In [12]:
import numpy as np

In [13]:
kernel = np.array([[4, 3, 3 ],[5, 5, 5] ,[2, 4, 3]])
kernel

array([[4, 3, 3],
       [5, 5, 5],
       [2, 4, 3]])

In [14]:
backp = np.zeros((5,5))

In [15]:
backp[1][2]

0.0

In [16]:
for i in range(5):
    for j in range(5):
        for a in range(min(3,i+1,5-i)):
            for b in range(min(3,j+1,5-j)):
                backp[i][j] += kernel[max(min(i-a,2),0)][max(min(j-b,2),0)]

In [17]:
backp

array([[ 4.,  7., 10.,  6.,  3.],
       [ 9., 17., 25., 16.,  8.],
       [11., 23., 34., 22., 11.],
       [ 4., 12., 18., 12.,  6.],
       [ 2.,  6.,  9.,  6.,  3.]])

In [18]:
import torch
import torch.nn as nn

In [19]:
t = torch.Tensor(backp.reshape(1,5,5))
t.shape

torch.Size([1, 5, 5])

In [30]:

m = nn.MaxPool2d(2,stride =1,padding=0)
output = m(t)
output

tensor([[[17., 25., 25., 16.],
         [23., 34., 34., 22.],
         [23., 34., 34., 22.],
         [12., 18., 18., 12.]]])

In [24]:
avg = nn.AvgPool2d(2,padding=1,stride = 2)
avg(t)

tensor([[[ 1.0000,  4.2500,  2.2500],
         [ 5.0000, 24.7500, 14.2500],
         [ 1.5000, 11.2500,  6.7500]]])

In [28]:
lp = nn.LPPool2d(1,2,stride =1)
lp(t)

tensor([[[37., 59., 57., 33.],
         [60., 99., 97., 57.],
         [50., 87., 86., 51.],
         [24., 45., 45., 27.]]])